export const elements = {
  modeSurah: document.getElementById('modeSurah') as HTMLButtonElement,
  modeJuz: document.getElementById('modeJuz') as HTMLButtonElement,
  listHeader: document.getElementById('listHeader') as HTMLDivElement,
  listContainer: document.getElementById('listContainer') as HTMLDivElement,
  bookmarkList: document.getElementById('bookmarkList') as HTMLDivElement,
  notice: document.getElementById('notice') as HTMLDivElement,
  toastHost: document.getElementById('toastHost') as HTMLDivElement,
  selectionHeader: document.getElementById('selectionHeader') as HTMLDivElement,
  versesContainer: document.getElementById('versesContainer') as HTMLDivElement,
  playerBar: document.getElementById('playerBar') as HTMLDivElement,
  settingsDrawer: document.getElementById('settingsDrawer') as HTMLDivElement,
  settingsOverlay: document.getElementById('settingsOverlay') as HTMLDivElement,
  settingsContent: document.getElementById('settingsContent') as HTMLDivElement,
  readerOverlay: document.getElementById('readerOverlay') as HTMLDivElement,
  mobileNav: document.getElementById('mobileNav') as HTMLDivElement,
  mobileNavOverlay: document.getElementById('mobileNavOverlay') as HTMLDivElement,
  mobileTabSurah: document.getElementById('mobileTabSurah') as HTMLButtonElement,
  mobileTabJuz: document.getElementById('mobileTabJuz') as HTMLButtonElement,
  mobileTabBookmarks: document.getElementById('mobileTabBookmarks') as HTMLButtonElement,
  mobileSurahList: document.getElementById('mobileSurahList') as HTMLDivElement,
  mobileJuzList: document.getElementById('mobileJuzList') as HTMLDivElement,
  mobileBookmarkList: document.getElementById('mobileBookmarkList') as HTMLDivElement
};
